name : Train and Save the Model

on: 
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  matrix:
    name : Train and Save the Model
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python: [3.12 , 3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: install Requirements
        run: python -m pip install -r requirements.txt

      - name: Train the Model
        run: |
          python train.py
          ls -la artifacts
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: ml-artifact-${{ matrix.python }}-${{github.run_id}}
          path: artifacts